apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: lotus-redis
  labels:
    app: redisNode
    tier: node
spec:
  serviceName: lotus-redis
  replicas: 1
  selector:
    matchLabels:
      app: redisnode
      tier: node
  serviceName: redisnode
  template:
    metadata:
      labels:
        app: redisnode
        tier: node
    spec:
      hostname: lotus-redis
      subdomain: fil-lotus-devnet
      containers:
        - name: lotus-node
          image: redis:6-alpine
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 6379
              name: redis
              protocol: TCP
          env:
            - name: ALLOW_EMPTY_PASSWORD
              value: "yes"
      dnsPolicy: ClusterFirstWithHostNet
---
apiVersion: v1
kind: Service
metadata:
  name: lotus-redis
  labels:
    run: lotus-redis
spec:
  ports:
  - port: 6379
    protocol: TCP
  selector:
    app: redisnode
